name: Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Set up gems
      run: |
        gem install bundler -v 2.2.15
        bundle install
        bundle exec rake
    - name: Run rspec
      run: rspec spec
    - name: Run rubocop
      run: rubocop